---
- hosts: 192.168.56.101
  tasks:
    - name: Install the spacewalk client packages
      yum:
        name:
          - rhn-client-tools
          - rhn-check
          - rhn-setup
          - rhnsd
          - m2crypto
          - yum-rhn-plugin
        state: installed
    - name: add the client in to the spacewalk 
      rhn_register:
        state: present
        activationkey: 1-d15939872cdc602f1c8d367d8196144f
        username : admin
        password: redhat
        server_url: http://192.168.56.104/XMLRPC
